flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired

from flask_blog.models import Category

categories = {1: 'Бизнес', 2: 'Культура', 3: 'Спорт', 4: 'Еда', 5: 'Политика', 6: 'Знаменитости', 7: 'Стартапы',
              8: 'Путешествия'}


class PostForm(FlaskForm):
    title = StringField('Заголовок:', validators=[DataRequired()])
    category = SelectField('Тема:', coerce=int)
    content = TextAreaField('Текст статьи:', validators=[DataRequired()])
    submit = SubmitField('Опубликовать')

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, u"%s" % category.name) for category in Category.query.order_by('name')]
        self.category.choices.insert(0, (0, u"Не выбрана"))

flask_blog/main/routes.py
from flask import render_template, Blueprint, request

from flask_login import login_required

from flask_blog.models import Post
from flask_blog.users.utils import admin_login_required


main = Blueprint('main', __name__)


@main.route("/")
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('index.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html')


@main.route("/contact")
def contact():
    return render_template('contact.html')

flask_blog/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, category_id=int(form.category.data), content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('users.user_posts', username=current_user.username))
    return render_template('create_post.html', title='Новый пост', form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.category.data = post.category_id
        form.content.data = post.content
        return render_template('create_post.html', title='Обновление поста', form=form, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('users.user_posts', username=current_user.username))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.avatar = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        avatar = url_for('static', filename='profile_pics/' + current_user.avatar)
        return render_template('account.html', title='Аккаунт',
                               avatar=avatar, form=form, posts=posts,
                               user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/user/<string:username>")
@login_required
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

flask_blog/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>

    <title>
        {% block title %}
            {% if title %}
                Наш блог - {{ title }}
            {% else %}
                Наш блог
            {% endif %}
        {% endblock title %}
    </title>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">

    <!-- Template Main CSS Files -->
    <link href="{{ url_for('static', filename='css/variables.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    {% block css %}
    {% endblock %}

    <!-- =======================================================
    * Template Name: ZenBlog - v1.0.0
    * Template URL: https://bootstrapmade.com/zenblog-bootstrap-blog-template/
    * Author: BootstrapMade.com
    * License: https:///bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>
<!-- ======= Header ======= -->
<header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="{{ url_for('main.index') }}" class="logo d-flex align-items-center">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="assets/img/logo.png" alt=""> -->
            <h1>Наш блог</h1>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="/">Блог</a></li>
                <li class="dropdown"><a href="#"><span>Темы</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>
                        <li><a href="#">Бизнес</a></li>
                        <li><a href="#">Культура</a></li>
                        <li><a href="#">Спорт</a></li>
                        <li><a href="#">Еда</a></li>
                        <li><a href="#">Политика</a></li>
                        <li><a href="#">Знаменитости</a></li>
                        <li><a href="#">Стартапы</a></li>
                        <li><a href="#">Путешествия</a></li>
                    </ul>
                </li>
                <li><a href="/about">О нас</a></li>
                <li><a href="/contact">Контакты</a></li>
                {% if current_user.is_authenticated %}
                    <li class="dropdown"><a href="{{ url_for('users.account') }}"><span></span>
                        Привет, {{ current_user.username }}!<i
                                class="bi bi-chevron-down dropdown-indicator"></i></a>
                        <ul>
                            {% if current_user.is_admin %}
                                <li><a href="/admin">Административная панель</a></li>
                            {% endif %}
                            <li><a href="{{ url_for('users.account') }}">Личный кабинет</a></li>
                            <li><a href="{{ url_for('users.user_posts', username=current_user.username) }}">Мои
                                статьи</a></li>
                            <li><a href="{{ url_for('users.logout') }}">Выйти</a></li>
                        </ul>
                    </li>

                {% else %}
                    <li><a href="{{ url_for('users.login') }}"><span class="bi-person-circle"> </span> Войти</a></li>
                {% endif %}
            </ul>
        </nav><!-- .navbar -->

        <ul class="position-relative">
            <a href="#" class="mx-2"><span class="bi-facebook"></span></a>
            <a href="#" class="mx-2"><span class="bi-twitter"></span></a>
            <a href="#" class="mx-2"><span class="bi-instagram"></span></a>

    </div>

    </div>

</header><!-- End Header -->

{% block content %}
{% endblock %}
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">

    <div class="footer-content">
        <div class="container">

            <div class="row g-5">
                <div class="col-lg-4">
                    <h3 class="footer-heading">О нашем блоге</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam ab, perspiciatis beatae autem
                        deleniti voluptate nulla a dolores, exercitationem eveniet libero laudantium recusandae officiis
                        qui aliquid blanditiis omnis quae. Explicabo?</p>
                    <p><a href="about.html" class="footer-link-more">Learn More</a></p>
                </div>
                <div class="col-6 col-lg-2">
                    <h3 class="footer-heading">Навигация</h3>
                    <ul class="footer-links list-unstyled">
                        <li><a href="/"><i class="bi bi-chevron-right"></i> Блог</a></li>
                        <li><a href="/category"><i class="bi bi-chevron-right"></i> Темы</a></li>
                        <li><a href="/about"><i class="bi bi-chevron-right"></i> О нас</a></li>
                        <li><a href="/contact"><i class="bi bi-chevron-right"></i> Контакты</a></li>
                    </ul>
                </div>
                <div class="col-6 col-lg-2">
                    <h3 class="footer-heading">Темы</h3>
                    <ul class="footer-links list-unstyled">
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Бизнес</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Культура</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Спорт</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Еда</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Политика</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Знаменитости</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Стартапы</a></li>
                        <li><a href="category.html"><i class="bi bi-chevron-right"></i> Путешествия</a></li>

                    </ul>
                </div>

                <div class="col-lg-4">
                    <h3 class="footer-heading">Последние публицкации</h3>

                    <ul class="footer-links footer-blog-entry list-unstyled">
                        <li>
                            <a href="single-post.html" class="d-flex align-items-center">
                                <img src="{{ url_for('static', filename='img/post-sq-1.jpg') }}" alt=""
                                     class="img-fluid me-3">
                                <div>
                                    <div class="post-meta d-block"><span class="date">Стартапы</span> <span
                                            class="mx-1">&bullet;</span>
                                        <span>Jul 5th '22</span></div>
                                    <span>5 Great Startup Tips for Female Founders</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="single-post.html" class="d-flex align-items-center">
                                <img src="{{ url_for('static', filename='img/post-sq-2.jpg') }}" alt=""
                                     class="img-fluid me-3">
                                <div>
                                    <div class="post-meta d-block"><span class="date">Спорт</span> <span class="mx-1">&bullet;</span>
                                        <span>Jul 5th '22</span></div>
                                    <span>What is the son of Football Coach John Gruden, Deuce Gruden doing Now?</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="single-post.html" class="d-flex align-items-center">
                                <img src="{{ url_for('static', filename='img/post-sq-3.jpg') }}" alt=""
                                     class="img-fluid me-3">
                                <div>
                                    <div class="post-meta d-block"><span class="date">Бизнес</span> <span class="mx-1">&bullet;</span>
                                        <span>Jul 5th '22</span></div>
                                    <span>Life Insurance And Pregnancy: A Working Mom’s Guide</span>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a href="single-post.html" class="d-flex align-items-center">
                                <img src="{{ url_for('static', filename='img/post-sq-4.jpg') }}" alt=""
                                     class="img-fluid me-3">
                                <div>
                                    <div class="post-meta d-block"><span class="date">Бизнес</span> <span class="mx-1">&bullet;</span>
                                        <span>Jul 5th '22</span></div>
                                    <span>How to Avoid Distraction and Stay Focused During Video Calls?</span>
                                </div>
                            </a>
                        </li>

                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="footer-legal">
        <div class="container">

            <div class="row justify-content-between">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    <div class="copyright">
                        © Copyright <strong><span>ZenBlog</span></strong>. All Rights Reserved
                    </div>

                    <div class="credits">
                        <!-- All the links in the footer should remain intact. -->
                        <!-- You can delete the links only if you purchased the pro version. -->
                        <!-- Licensing information: https://bootstrapmade.com/license/ -->
                        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
                        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                    </div>

                </div>

                <div class="col-md-6">
                    <div class="social-links mb-3 mb-lg-0 text-center text-md-end">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="google-plus"><i class="bi bi-skype"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>

                </div>

            </div>

        </div>
    </div>

</footer>

<a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/php-email-form/validate.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ url_for('static', filename='js/main.js') }}"></script>


</body>

</html>

flask_blog/templates/login.html
{% extends "base.html" %}
{% block content %}
    <main id="login">
        <section id="posts" class="posts">
            <div class="container-fluid d-flex h-100 justify-content-center align-items-center " data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2 class="page-title mt-5">Авторизация</h2>
                    </div>
                    <div class="form col-lg-12">
                        <form action="" method="post" role="form">
                            {{ form.hidden_tag() }}

                            <div class="form-group col-md-12">
                                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.email(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>


                            <div class="form-group col-md-12">
                                {{ form.password.label(class="form-control-label") }}
                                {% if form.password.errors %}
                                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.password(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>

                            <div class=" form-group form-check">
                                {{ form.remember(class="form-check-input") }}
                                {{ form.remember.label(class="form-check-label") }}
                            </div>

                            <div class="form-group">
                                {{ form.submit(class="btn btn-dark") }}
                                <small class="text-muted ms-2">
                                    <a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
                                </small>
                            </div>
                        </form>
                        <small style="font-size: 15px; font-weight: 500;">
                            <a class="mt-4" href="{{ url_for('users.register') }}">Нужен аккаунт?
                                Зарегистрируйтесь!</a>
                        </small>

                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

flask_blog/templates/post.html
{% extends "base.html" %}
{% block content %}
    <section id="posts" class="posts">
        <div class="container mt-5" style="display: flex;">
            <article class="media mt-3 me-3" style="display: flex; flex-direction: column;">
                <img class="rounded-circle article-img" style="margin-right: 5px;"
                     src="{{ url_for('static', filename='profile_pics/' + post.author.avatar) }}">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}"
                   style="margin: 0 auto">{{ post.author.username }}</a>
            </article>
            <div class="row mt-3 mb-5">
                <div class="card" style="margin-bottom: 20px;">
                    <div class="card-body">
                        <h4 class="card-title">{{ post.title }}</h4>
                        <small>Тема - {{ post.category.name }}</small>
                        <br>
                        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
                        <br>
                        <br>
                        <p class="card-text">{{ post.content }}</p>
                    </div>
                    <div class="card-footer" style="font-size: 20px;">
                        <!-- <i class="fa fa-heart-o"></i>
                        <i class="fa fa-bookmark-o"></i> -->
                        {% if post.author == current_user %}
                            <div class="card-footer" style="font-size: 20px;">
                                {% if post.author == current_user %}
                                    <a class="btn btn-secondary btn-sm mt-1 mb-1"
                                       href="{{ url_for('posts.update_post', post_id=post.id) }}">Редактировать</a>
                                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal"
                                            data-bs-target="#deleteModal">Удалить
                                    </button>

                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Удалить пост?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Удалить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

flask_blog/templates/reset_request.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="content-section mt-5">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Сброс пароля</legend>
                    <div class="form-group col-md-4">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group mt-3 mb-3">
                    {{ form.submit(class="btn btn-dark") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

flask_blog/templates/user_posts.html
{% extends "base.html" %}
{% block content %}

    <main id="main">

        <!-- ======= Post Grid Section ======= -->
        <section id="posts" class="posts">
            <div class="container" data-aos="fade-up">
                <div class="row mt-2 mb-5">
                    <button class="btn btn-success col-lg-2"><a href="{{ url_for('posts.new_post') }}">Новая статья</a>
                    </button>
                </div>
                <div class="row g-5">
                    {% for post in posts.items %}
                        <div class="col-lg-12">
                            <div class="post-entry-1 lg">
                                <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">
                                    {{ post.title }}
                                </a></h2>
                                <div class="post-meta"><span class="date">{{ post.category.name }}</span> <span
                                        class="mx-1">&bullet;</span>
                                    <span>{{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</span></div>


                                <div style="display: flex;">
                                    <button class="btn btn-secondary me-2"><a
                                            href="{{ url_for('posts.update_post', post_id=post.id) }}">Редактировать</a>
                                    </button>
                                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                                        <input class="btn btn-danger" type="submit" value="Удалить">
                                    </form>

                                </div>
                            </div>

                        </div>

                    {% endfor %}
                </div> <!-- End .row -->
            </div>
        </section> <!-- End Post Grid Section -->


    </main><!-- End #main -->

{% endblock %}